### ISSUE TITLE
Look into recording panels

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#10]
I School may have facilities, otherwise Dav & Anthony can hack something together.

**Comment by davclark** [comment]
Nice to have:
- [ ] Individual mics for each speaker
- [ ] 1-2 room / wireless mics
- [ ] Video (Dav or Anthony can provide camera, BIDS has tripod)
- [ ] Commitment to an editing / production process (I School has staff?)

**Comment by anthonysuen** [comment]
Do you want to follow up with I School about this? Kevin Hart does the recordings there. You could pitch it as content relevant to MIDS students.

**Comment by davclark** [comment]
That would be ideal. Should I just contact Kevin? Or get an introduction from you (or go via Anno)?

I don't want to mix this up with MIDS. I'd request you not even bring that up.

**Comment by davclark** [comment]
@anthonysuen has contacted Kevin Hart - but I haven't heard back yet.

**Comment by davclark** [comment]
This never got done.

**Comment by anthonysuen** [comment]
The I School said they would not be doing this for this class. I thought we were going to try to get Temina to record some of the lectures.
