### ISSUE TITLE
Fix some logos

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#19]
Anno sent a better I School Logo, use BIDS logo without background (maybe BIDS collaborative logo?)

cc: @anthonysuen

**Comment by anthonysuen** [comment]
Agreed. Will update with a BIDS Collaborative logo.

**Comment by anthonysuen** [comment]
Here is the BIDS Collaborative logo for future use. 

![bids collaborative logo](https://cloud.githubusercontent.com/assets/2729194/8483920/20080040-20a9-11e5-8e44-31e317fc3164.png)
