### ISSUE TITLE
Get funding document ready

### ISSUE THREAD

**Issue by anthonysuen** [hackingmeasurement/hackingmeasurement.github.io#23]
Elements include: Support for various courses, Public Impact, and Scaling to UC wide initiative!

**Comment by davclark** [comment]
So, hilariously, Javier's appointment was a stop-gap to make sure he's funded and can work on this stuff. So, please proceed to try to get funding to pay for him at ~25% GSR (note: not GSI).

**Comment by anthonysuen** [comment]
Cool. Let me know if you want to make any changes to the proposed document.
