### ISSUE TITLE
Decide on software stack for programming arduinos

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#29]
In particular:
- [ ] What language to connect with Arduino:
  - [Processing](http://playground.arduino.cc/Interfacing/Processing)
  - Python

What did Falk do to connect to arduino to the base-station? Should be somewhere in the issue tracker / wiki on http://github.com/glass-bead-labs

**Comment by jnaulty** [comment]
@davclark There's also javascript
https://github.com/rwaldron/johnny-five

**Comment by davclark** [comment]
This appears to have been decided. @jnaulty thanks for the tip to johnny-five. JavaScript is the future. Though I am not sure if that's because it was the least thoughtfully designed language, and we are hella punk or what...
