### ISSUE TITLE
Summary for sensor building and management

### ISSUE THREAD

**Issue by javirosa** [hackingmeasurement/hackingmeasurement.github.io#32]
Needed for introductory class.

**Comment by javirosa** [comment]
Add information on:
- What materials to get.
- What sensors are available.
- Topics to be covered.
  - Scale-up
  - Introduction to sensors
  - Advanced data collection using Arduinos
  - Data management

**Comment by davclark** [comment]
I have just made you the other unmoderated person for posting to hackingmeasurement@lists.berkeley.edu

You will have two grad students (if all goes according to plan) for each class. Feel free to reach out ahead of class and help with setting up the page for the syllabus that day. 

Also editing the above to show you how nice it is when you use real markdown. :tongue:

**Comment by davclark** [comment]
@javirosa I guess you removing yourself here means it's closed? Feel free to reopen.
