### ISSUE TITLE
Get everybody's github id

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#33]
At a minimum, leave your github ID here. If you're comfortable, also leave your name. If you're not comfortable linking your name, please also email me your github id (from your berkeley.edu account is most secure / private).

**Comment by alankrita-dayal** [comment]
ID: alankrita-dayal
Alankrita Dayal

**Comment by ProximaDas** [comment]
Github ID : ProximaDas
Proxima DasMohapatra

**Comment by nhejab** [comment]
ID: nhejab

**Comment by edrubin** [comment]
edrubin
Ed Rubin

**Comment by swuerth** [comment]
swuerth
Stephanie Wuerth

**Comment by angelikirk** [comment]
angelikirk

**Comment by tmadon** [comment]
tmadon
Temina Madon

**Comment by sfwatergit** [comment]
Sfwatergit/Sid Feygin

**Comment by saraaissa** [comment]
saraaissa
Sara Litke

**Comment by vhutheesing** [comment]
vhutheesing
Vivek Hutheesing (not registered)

**Comment by davclark** [comment]
Everyone above this line has been added to the new class team list, but we're still missing most of the folks in the class...
