### ISSUE TITLE
Update first day to reflect BIDS / BIDS collaborative distinction

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#35]
@anthonysuen I wanted you to have a look at how one person interpreted your talk! Good to take in for future presentations, as BIDS is actually even more bombastic than what got captured (and we are but a humble part).

Can you take a crack at updating [the notes from our first day](http://hackingmeasurement.berkeley.edu/syllabus/2015/08/27/welcome.html)?
You can edit directly through the web [here](https://github.com/hackingmeasurement/hackingmeasurement.github.io/blob/master/syllabus/_posts/2015-08-27-welcome.md).

**Comment by davclark** [comment]
Focusing on the issue, I neglected to say good job, and I'm glad I pushed you to include that segment!

**Comment by davclark** [comment]
@anthonysuen this is something you could do to help. We could use more coherency, and a good way to do this is in text!

**Comment by anthonysuen** [comment]
Seems all that needs to be added was the word Collaborative.

**Comment by davclark** [comment]
Actually - I think you're right! But I'm not sure you get the underlying point I'm trying to make - that the presentation was not clear on the difference between BIDS and the BIDS Collaborative. This is important for keeping Kevin and others comfortable with our own communications efforts.
