### ISSUE TITLE
Many Labs Air Pollution Pic

### ISSUE THREAD

**Issue by anthonysuen** [hackingmeasurement/hackingmeasurement.github.io#39]
![los-angeles-smog-1](https://cloud.githubusercontent.com/assets/2729194/9623929/847f748a-50fc-11e5-9f45-7b3b67c5736f.jpg)

**Comment by davclark** [comment]
Is this moved into the repo? This is not a stable place for this...

**Comment by davclark** [comment]
OK - 5 days have passed. Closing.
