### ISSUE TITLE
Transition main BIDS Collaborative site from WordPress to Github

### ISSUE THREAD

**Issue by anthonysuen** [hackingmeasurement/hackingmeasurement.github.io#40]

**Comment by davclark** [comment]
So exciting! I think we need to make a sub-plan:
- [ ] Identify sitemap, mapping onto new site (or just replicate exactly)
- [ ] Assign roles
- [ ] Start new issues for sub-tasks

**Comment by davclark** [comment]
Also - is this going to go into Hacking Measurement? It seems like it shouldn't... maybe a new repo?

**Comment by anthonysuen** [comment]
Agreed. Lets use the BIDS (DSC) Facilitation repo again.

On Fri, Sep 4, 2015 at 2:40 PM, Dav Clark notifications@github.com wrote:

> Also - is this going to go into Hacking Measurement? It seems like it
> shouldn't... maybe a new repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS-collaborative/hackingmeasurement.github.io/issues/40#issuecomment-137859065
> .

## 

Anthony Suen
Data Science Fellow
Berkeley Institute for Data Science
http://vcresearch.berkeley.edu/datascience/overview-berkeley-institute-for-data-science
190 Doe Library
UC Berkeley
Berkeley, CA 94720-2190

**Comment by davclark** [comment]
Moved [here](/BIDS-collaborative/dsc-facilitation/issues/29).
