### ISSUE TITLE
Create project / application schema

### ISSUE THREAD

**Issue by davclark** [hackingmeasurement/hackingmeasurement.github.io#8]
Examples:
- [General Assembly](https://docs.google.com/forms/d/1UQt4nCBqTfqfOtUhU7XiMMduqHJm0VObigtYnza9L7s/viewform)
- [BluePrint](http://bptech.berkeley.edu/apply)
- [DIL Social Innovator OnRamp](https://docs.google.com/forms/d/1Akm88SA70OXs9PjUxMjdErK7gm4PdTEZC-wa-cPuXkc/viewform)

**Comment by anthonysuen** [comment]
I have been working on a version here:
https://docs.google.com/forms/d/17R1Pjy70x7zI-2QcYnOnYrEGcTXcLx7ma-5ueadYpBw/edit
Hope to have it done for students and projects by tomorrow.

**Comment by davclark** [comment]
Cool - I made some minor edits. Is there a similar project form yet?

On Sun, Jun 14, 2015 at 11:47 PM, anthonysuen notifications@github.com
wrote:

> I have been working on a version here:
> 
> https://docs.google.com/forms/d/17R1Pjy70x7zI-2QcYnOnYrEGcTXcLx7ma-5ueadYpBw/edit
> Hope to have it done for students and projects by tomorrow.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/hackingmeasurement/hackingmeasurement.github.io/issues/8#issuecomment-111953339
> .

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by anthonysuen** [comment]
Here is the project application form. https://docs.google.com/forms/d/1qBn0Rh8UJ8mfambK7_R5Dox5rXPdEsxYkcmO7VgG7Wk/edit

**Comment by anthonysuen** [comment]
Yes. I am working on it right now.

Anthony

On Mon, Jun 15, 2015 at 12:26 AM, Dav Clark notifications@github.com
wrote:

> Cool - I made some minor edits. Is there a similar project form yet?
> 
> On Sun, Jun 14, 2015 at 11:47 PM, anthonysuen notifications@github.com
> wrote:
> 
> > I have been working on a version here:
> > 
> > https://docs.google.com/forms/d/17R1Pjy70x7zI-2QcYnOnYrEGcTXcLx7ma-5ueadYpBw/edit
> > Hope to have it done for students and projects by tomorrow.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/hackingmeasurement/hackingmeasurement.github.io/issues/8#issuecomment-111953339
> > 
> > .
> 
> ## 
> 
> Dav Clark
> Data Scientist
> Berkeley D-Lab + BIDS
> bead.glass
> 917-544-8408
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackingmeasurement/hackingmeasurement.github.io/issues/8#issuecomment-111965640
> .

## 

Anthony Suen

**Comment by davclark** [comment]
Another nice example from @anthonysuen

**Comment by anthonysuen** [comment]
Strange I don't know what happened to my application pages. They were completed as of last week.

**Comment by anthonysuen** [comment]
Wow. The biggest reason I hate Google Drive. I made this under another account and could not find it. FSF. https://docs.google.com/forms/d/1qBn0Rh8UJ8mfambK7_R5Dox5rXPdEsxYkcmO7VgG7Wk/edit
